### ISSUE TITLE
Bosses that have faces only have eyes (Switch)

### ISSUE THREAD

**Issue by camohere** [Kobazco/Miitopia_Randomizer#9]
Normally, in Miitopia, bosses have faces, and I understand later in the game when you refight bosses, they only have some features, but my problem is that when you fight a boss, no face is there! I do not know if this is a problem for anyone else, but this is annoying me alot. I'll send an image. 
![damn it](https://user-images.githubusercontent.com/126398756/232238661-a6fb7fac-1932-47cf-9b70-68c72fe0f9e8.PNG)

**Comment by camohere** [comment]
I saw other people fighting other bosses with faces, so (i hope) im not just being stupid and this isn't an issue at all.

**Comment by Kobazco** [comment]
I think in the last update I removed bosses having their casted faces due to soft locks with NPCs faces being saved. Although at the same time, I'm pretty sure I did not take this feature out. Either way, will double check soon.
